USE notes;
SET CHARSET UTF8;

-- いったんテーブルを削除
DROP TABLE IF EXISTS Sessions;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS ChatTopics;
DROP TABLE IF EXISTS ChatHistory;
DROP TABLE IF EXISTS Users;

-- セッションテーブル
CREATE TABLE Sessions (
    SessionID VARCHAR(128) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    Expires INT UNSIGNED NOT NULL,
    Data MEDIUMTEXT COLLATE utf8mb4_bin
);

-- ユーザーテーブル
CREATE TABLE Users (
    UserID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ブックテーブル
CREATE TABLE Books (
    BookID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    UserID BINARY(16) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- ノートテーブル
CREATE TABLE Notes (
    NoteID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    BookID BINARY(16) NOT NULL,
    Title VARCHAR(255),
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (BookID) REFERENCES Books(BookID)
);

-- チャットトピックテーブル
CREATE TABLE ChatTopics (
    TopicID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    UserID BINARY(16) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- チャット履歴テーブル
CREATE TABLE ChatHistory (
    ChatID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    UserID BINARY(16) NOT NULL,
    TopicID BINARY(16) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Message TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);